### PR TITLE
69 control animation playback

### LINKED ISSUE #69: Control animation playback
As a User, I want to be able to pause and replay the outcome of a scenario so that I can better understand why it may be important.

- [x] Create UI and video overlay for displaying Animations
	- [x] Pause button pauses and unpauses the animation
	- [x] Replay button shows up after the animation has finished and restarts the animation from the beginning.

### PR DESCRIPTION
**Pull request by IVidackovic**
Closes #69

- Add video UI 
- Implemented the method for setting the url path to the video player

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by GeorgZs — DISMISSED** [review]
Looking good, nice of you to leave a TODO comment for whoever is adding the animations!

**Comment by JohnWebb00** [comment]
I don't see where you implemented the pause and replay buttons for the Video UI. Could you clarify this?

**Review by bardiaForooraghi — COMMENTED** [review]
Did you connect the check answer button to the player? So whenever we press the check answer button, the animation is displayed; if the question does not have an animation, nothing is displayed.

**Comment by IVidackovic** [comment]
> I don't see where you implemented the pause and replay buttons for the Video UI. Could you clarify this?

My implementation includes play and pause button in the UI, so its only visible when a video is playing.

**Comment by IVidackovic** [comment]
> Did you connect the check answer button to the player? So whenever we press the check answer button, the animation is displayed; if the question does not have an animation, nothing is displayed.

Okey, will add this feature and re-request a review.

**Review by GeorgZs — APPROVED** [review]

**Pull request merged**
